@startuml
' Modelo de Dados - SafeRoute360

entity Sensor {
  *id: int <<PK>>
  localizacao: string
  nivel_cm: decimal
  data_hora: datetime
}

entity Alerta {
  *id: int <<PK>>
  id_sensor: int <<FK>>
  nivel_cm: decimal
  mensagem: string
  data_hora: datetime
}

entity Abrigo {
  *id: int <<PK>>
  nome: string
  localizacao: string
  capacidade: int
  ocupacao_atual: int
  telefone: string
}

Sensor ||--o{ Alerta : gera

@enduml
