-- 🟢 Criação da tabela de Sensores
CREATE TABLE sensores (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      localizacao VARCHAR2(100) NOT NULL,
      nivel_cm NUMBER(5,2) NOT NULL,
      data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 🟡 Criação da tabela de Alertas
CREATE TABLE alertas (
     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     id_sensor NUMBER NOT NULL,
     nivel_cm NUMBER(5,2) NOT NULL,
     mensagem VARCHAR2(200),
     data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     CONSTRAINT fk_alerta_sensor FOREIGN KEY (id_sensor) REFERENCES sensores(id)
);

-- 🛑 Criação da tabela de Abrigos
CREATE TABLE abrigos (
     id_abrigo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     nome VARCHAR2(100) NOT NULL,
     localizacao VARCHAR2(150) NOT NULL,
     capacidade INT NOT NULL,
     ocupacao_atual INT DEFAULT 0,
     telefone VARCHAR2(20)
);